server:
  port:8080

spring:
  datasource:
    username: root
    password: pass
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    hibernate:
      ddl-auto: update
    show-sql: true

# example values

indexing-settings:
  sites:
#    - url: https://lenta.ru
#      name: Лента.ру

#    - url: https://skillbox.ru
#      name: Skillbox

#    - url: https://www.playback.ru
#      name: PlayBack.Ru

#    - url:  https://smarfony.ru
#      name: Смартфоны.ру

#    - url: https://radiomv.ru
#      name: Милицейская волна

#    - url: https://volochek.life/
#      name: Вышний Волочёк
#    - url: https://ipfran.ru/
#      name: Федеральный исследовательский центр
#    - url: https://dimonvideo.ru/
#      name: ДимонВидео

    - url: https://et-cetera.ru/mobile/
      name: Театр Et Cetera

    - url: https://lenkom.info/
      name: ТЕАТР Ленком