server:
  port:8080

spring:
  datasource:
    username: root
    password: pass
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# example values

indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
